### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [azatnv/RusCheckers#1]
1. https://github.com/azatnv/RusCheckers/blob/553f0650b46b2895dbd5da2219d4c15c334285d0/src/main/MainController.java#L22-L45

Такого кода быть точно не должно. Подумайте, как сделать нормально.

2. https://github.com/azatnv/RusCheckers/blob/553f0650b46b2895dbd5da2219d4c15c334285d0/src/main/MainController.java#L61-L62

Статического изменяемого состояния быть не должно, это плохой стиль. Попробуйте ввести понятие поля (в виде класса, например)

3. Постарайтесь избавиться от дублирования кода, хотя бы там, где об этом предупреждает IDE.

4. Магические числа лучше заменить константами и перечислениями.

5. Нет проверки обязательного взятия (вернее, его начала).

6. Длинное взятие прерывается, если шашка превратилась в дамку.

**Comment by azatnv** [comment]
(1) Этот код является аннотацией для объявления элементов из fxml - файла по их атрибутам fx: id. Я пока не знаю, как сделать этот код еще проще.
(2-5) Исправил
(6) По-моему, если при взятии шашка становится дамкой, то будучи дамкой она может продолжить это взятие. Цитирование правил: "Если простая шашка при взятии достигает последнего (восьмого от себя) горизонтального ряда она превращается в дамку. И если ей предоставляется возможность дальнейшего взятия шашек соперника, то она обязана тем же ходом сделать это."
