### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [azatnv/RusCheckers#2]
1. То, что в классе `Functions` как-то совсем не соответствует объектно-ориентированному стилю. Сделайте лучше класс, представляющий поле и методы на нём.
2. Во всём коде куча магических чисел (8, 7, 3). Вынесите их в статические константы с осмысленными именами.
3. В `findAllPossibleMoves` местами копипаста.
4. От десятков одинаковых `ImageView` тоже лучше бы избавиться.
5.  `Cells` представляет и тип ячейки на поле и текущего игрока, что не очень хорошо.
6. `curDepth` в `createNodes` вычисляется неверно. Там получается не текущая глубина, а просто число рассматриваемых ходов. На мысль об этом наводит следующее: поставьте `depth` в 2000 и запустите бота. Он работает почти так же, как и с `depth == 3`, то есть получается какой-то ultimate решатель. Посмотрите на `position` в дебаггере при первом вызове `miniMax` и увидите в чём, косяк.
7. Почти вся польза от альфа-бета отсечения убивается за счёт того, что изначально вы строите дерево, ничего не отсекая, а отсечение используете только при оценке позиций.

**Comment by azatnv** [comment]
Все замечания исправил
